name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  current-version:  # id of input
    description: 'Existing Version in year.month.day.counter format'
    required: true
    default: '2023.1.1.1'
outputs:
  new-version: # id of output
    description: 'New Version'
runs:
  using: 'node16'
  main: 'index.js'
